defmodule Przma.MixProject do
  use Mix.Project

  def project do
    [
      app:             :przma,
      version:         "0.4.0",
      elixir:          "~> 1.16",
      elixirc_paths:   elixirc_paths(Mix.env()),
      start_permanent: Mix.env() == :prod,
      aliases:         aliases(),
      deps:            deps()
    ]
  end

  def application do
    [
      mod:   {Przma.Application, []},
      extra_applications: [:logger, :runtime_tools, :crypto]
    ]
  end

  defp elixirc_paths(:test), do: ["lib", "test/support"]
  defp elixirc_paths(_),     do: ["lib"]

  defp deps do
  [
    # Phoenix core (already generated by mix phx.new — keep as-is)
    {:phoenix,            "~> 1.7"},
    {:phoenix_pubsub,     "~> 2.1"},
    {:bandit,             "~> 1.2"},
    {:ecto_sql,           "~> 3.11"},
    {:postgrex,           "~> 0.17"},
    {:jason,              "~> 1.4"},
    {:telemetry_metrics,  "~> 1.0"},
    {:telemetry_poller,   "~> 1.0"},
    {:gettext,            "~> 0.26"},

    # PRZMA additions
    {:horde,              "~> 0.9"},
    {:oban,               "~> 2.17"},
    {:broadway,           "~> 1.0"},
    {:req,                "~> 0.4"},
    {:finch,              "~> 0.18"},
    {:msgpax,             "~> 2.3"},
    {:uniq,               "~> 0.6"},
    {:explorer,           "~> 0.8"},
    {:ex_aws,             "~> 2.5"},
    {:ex_aws_s3,          "~> 2.4"},
    {:hackney,            "~> 1.20"},
    {:sweet_xml,          "~> 0.7"},
    {:hammer,             "~> 6.1"},
    {:jose,               "~> 1.11"},
    {:open_api_spex,      "~> 3.18"},

    # Dev/test
    {:ex_doc,             "~> 0.31", only: :dev,  runtime: false},
    {:credo,              "~> 1.7",  only: :dev,  runtime: false},
    {:mox,                "~> 1.1",  only: :test, runtime: false}
  ]
end
  defp aliases do
    [
      setup:         ["deps.get", "ecto.setup"],
      "ecto.setup":  ["ecto.create", "ecto.migrate", "run priv/repo/seeds.exs"],
      "ecto.reset":  ["ecto.drop", "ecto.setup"],
      test:          ["ecto.create --quiet", "ecto.migrate --quiet", "test"]
    ]
  end
end
