defmodule AlemWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :alem

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_alem_key",
    signing_salt: "LJI77cZd",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :alem,
    gzip: not code_reloading?,
    only: AlemWeb.static_paths(),
    raise_on_missing_only: false

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :alem
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json, Alem.Plug.MsgpackParser],
    pass: ["*/*"],
    validate_utf8: false,
    json_decoder: Phoenix.json_library(),
    length: 100_000_000,
    read_length: 1_000_000,
    read_timeout: 300_000

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options

  plug Corsica,
  origins: ["http://localhost:1420", "http://localhost:1422", "http://localhost:4000", "tauri://localhost"],
  allow_headers: :all,
  allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]

  plug AlemWeb.Router
end
